---
- name: install nginx
  yum: name=nginx state=present

- name: adding index.html
  copy: src=index.html dest=/usr/share/nginx/index.html


- name: start and enable nginx
  service: name=nginx state=started enabled=yes
  when: packer_builder_type == "amazon-ebs"

